# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='dmcr_protocol.proto',
  package='dmcr.Packet',
  serialized_pb='\n\x13\x64mcr_protocol.proto\x12\x0b\x64mcr.Packet\"*\n\x0cPacketHeader\x12\x0e\n\x06length\x18\x01 \x02(\r\x12\n\n\x02id\x18\x02 \x02(\r\"N\n\x10\x42\x61\x63kendHandshake\x12\x18\n\x10protocol_version\x18\x01 \x02(\r\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x02(\t\"\"\n\x10\x43onnectionResult\x12\x0e\n\x06result\x18\x01 \x02(\r\"W\n\x07NewTask\x12\n\n\x02id\x18\x01 \x02(\r\x12\r\n\x05width\x18\x02 \x02(\r\x12\x0e\n\x06height\x18\x03 \x02(\r\x12\x12\n\niterations\x18\x04 \x02(\r\x12\r\n\x05scene\x18\x05 \x02(\t\"|\n\x0cRenderedData\x12\n\n\x02id\x18\x01 \x02(\r\x12\r\n\x05width\x18\x02 \x02(\r\x12\x0e\n\x06height\x18\x03 \x02(\r\x12\x17\n\x0fiterations_done\x18\x04 \x02(\r\x12\x13\n\x0b\x64\x61ta_length\x18\x05 \x02(\r\x12\x13\n\x0b\x64\x61ta_format\x18\x06 \x02(\r\"\x16\n\x08QuitTask\x12\n\n\x02id\x18\x01 \x02(\r')




_PACKETHEADER = descriptor.Descriptor(
  name='PacketHeader',
  full_name='dmcr.Packet.PacketHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='length', full_name='dmcr.Packet.PacketHeader.length', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='id', full_name='dmcr.Packet.PacketHeader.id', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=36,
  serialized_end=78,
)


_BACKENDHANDSHAKE = descriptor.Descriptor(
  name='BackendHandshake',
  full_name='dmcr.Packet.BackendHandshake',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='protocol_version', full_name='dmcr.Packet.BackendHandshake.protocol_version', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='key', full_name='dmcr.Packet.BackendHandshake.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='description', full_name='dmcr.Packet.BackendHandshake.description', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=80,
  serialized_end=158,
)


_CONNECTIONRESULT = descriptor.Descriptor(
  name='ConnectionResult',
  full_name='dmcr.Packet.ConnectionResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='result', full_name='dmcr.Packet.ConnectionResult.result', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=160,
  serialized_end=194,
)


_NEWTASK = descriptor.Descriptor(
  name='NewTask',
  full_name='dmcr.Packet.NewTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='dmcr.Packet.NewTask.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='width', full_name='dmcr.Packet.NewTask.width', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='height', full_name='dmcr.Packet.NewTask.height', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='iterations', full_name='dmcr.Packet.NewTask.iterations', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='scene', full_name='dmcr.Packet.NewTask.scene', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=196,
  serialized_end=283,
)


_RENDEREDDATA = descriptor.Descriptor(
  name='RenderedData',
  full_name='dmcr.Packet.RenderedData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='dmcr.Packet.RenderedData.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='width', full_name='dmcr.Packet.RenderedData.width', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='height', full_name='dmcr.Packet.RenderedData.height', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='iterations_done', full_name='dmcr.Packet.RenderedData.iterations_done', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data_length', full_name='dmcr.Packet.RenderedData.data_length', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data_format', full_name='dmcr.Packet.RenderedData.data_format', index=5,
      number=6, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=285,
  serialized_end=409,
)


_QUITTASK = descriptor.Descriptor(
  name='QuitTask',
  full_name='dmcr.Packet.QuitTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='dmcr.Packet.QuitTask.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=411,
  serialized_end=433,
)

DESCRIPTOR.message_types_by_name['PacketHeader'] = _PACKETHEADER
DESCRIPTOR.message_types_by_name['BackendHandshake'] = _BACKENDHANDSHAKE
DESCRIPTOR.message_types_by_name['ConnectionResult'] = _CONNECTIONRESULT
DESCRIPTOR.message_types_by_name['NewTask'] = _NEWTASK
DESCRIPTOR.message_types_by_name['RenderedData'] = _RENDEREDDATA
DESCRIPTOR.message_types_by_name['QuitTask'] = _QUITTASK

class PacketHeader(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PACKETHEADER
  
  # @@protoc_insertion_point(class_scope:dmcr.Packet.PacketHeader)

class BackendHandshake(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BACKENDHANDSHAKE
  
  # @@protoc_insertion_point(class_scope:dmcr.Packet.BackendHandshake)

class ConnectionResult(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONNECTIONRESULT
  
  # @@protoc_insertion_point(class_scope:dmcr.Packet.ConnectionResult)

class NewTask(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _NEWTASK
  
  # @@protoc_insertion_point(class_scope:dmcr.Packet.NewTask)

class RenderedData(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RENDEREDDATA
  
  # @@protoc_insertion_point(class_scope:dmcr.Packet.RenderedData)

class QuitTask(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _QUITTASK
  
  # @@protoc_insertion_point(class_scope:dmcr.Packet.QuitTask)

# @@protoc_insertion_point(module_scope)
